version: '3'
 
services:
    apache_fpm:
        container_name: apache_fpm
        build:
            context: ./apache_fpm
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ./apache_fpm/logs:${APACHE_ROOT_DIR}/logs
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
            - PHP_IP=${PHP_IP}
            - PHP_APP_DIR=${PHP_APP_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    php_fpm:
        container_name: php_fpm
        build:
            context: ./php_fpm
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ./apache_fpm/htdocs:${PHP_APP_DIR}
            - ./php_fpm/logs/:${PHP_ROOT_DIR}/logs
        depends_on:
            - apache_fpm
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - APACHE_IP=${APACHE_IP}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    apache_php:
        container_name: apache_php
        build:
            context: ./apache_php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE2_ROOT_DIR}
        volumes:
            - ./apache_php/htdocs:${APACHE2_ROOT_DIR}
        networks:
            public_net:
                ipv4_address: ${APACHE2_IP}
    rproxy:
        container_name: rproxy
        build:
            context: ./rproxy
        ports:
            - ${RPROXY_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${RPROXY_IP}
        environment:
            - RPROXY_EXPOSED_PORT=${RPROXY_EXPOSED_PORT}
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
